- name: Install Node-exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz"
    dest: /opt/node_exporter-0.18.1.linux-amd64.tar.gz
    mode: 0755
- name: Extract tar file
  unarchive:
    src: /opt/node_exporter-0.18.1.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
- name: ansible create directory node_exporter
  file:
    path: /opt/node_exporter
    state: directory
- name: Copy Exporter
  copy:
    src: /opt/node_exporter-0.18.1.linux-amd64/node_exporter
    dest: /opt/node_exporter
    remote_src: yes
    mode: 0755
- name: Create Service
  ansible.builtin.template:
    src: node-exporter-service.j2
    dest: /usr/lib/systemd/system/node_exporter.service
- name: Servie daemon-reload node_exporter
  shell: systemctl daemon-reload
- name: Service start node_exporter
  shell: systemctl start node_exporter.service
- name: Service status node_exporter
  shell: systemctl status node_exporter.service
- name: Service enable node_exporter
  shell: systemctl enable node_exporter.service
